### ISSUE TITLE
Develop Initial Prototype

### ISSUE THREAD

**Issue by edolinsky** [pique-media/pique#16]
A working prototype which can gather and display data from the back-end will allow us to gather feedback and get the ball rolling on iterative development of the Pique front-end.

**Comment by MariaStrasky** [comment]
Just to clarify, does a working prototype mean that it will have data from multiple sources (Facebook, Twitter, etc.) and have support for Top, Trending, and Hashtag posts? Or is our current set up (with real posts displayed) enough to satisfy this?

**Comment by edolinsky** [comment]
Current set up is enough to satisfy this. Closing!
